spring:
  application:
    name: multicine
  datasource:
    url: jdbc:postgresql://localhost:30001/bd_multicine_test
    username: admin
    password: N0S3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080
